apiVersion: v1
kind: Service
metadata:
  name: apollo-gateway
  labels:
    iks-metric: actuator-prometheus
spec:
  selector:
    app: apollo-gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
    - name: iks-metric
      protocol: TCP
      port: 8490
      targetPort: 8490
      
