apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-router
  labels:
    app: apollo-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-router
  template:
    metadata:
      labels:
        app: apollo-router
    spec:
      containers:
      - name: apollo-router
        # image: ramapalaniappan436/apollo-router:0.42.0
        image: docker.intuit.com/api-management/rapidxgqlrouter/service/rp/apollo-router:latest
        ports:
          - containerPort: 4000
            name: apollo-router
            protocol: TCP
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 2
          timeoutSeconds: 2
          failureThreshold: 3
          httpGet:
            path: /.well-known/apollo/server-health
            port: 4000
            scheme: HTTP
        resources:
          requests:
            cpu: "1.5"
            memory: "3Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        volumeMounts:
        - name: supergraph
          mountPath: /etc/config
        - name: routerconfig
          mountPath: /dist/config
      volumes:
        - name: supergraph
          configMap:
            name: supergraph
        - name: routerconfig
          configMap:
            name: routerconfig